# sam ResNet18 widen_factor=1; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10

# sam ResNet18 widen_factor=2; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=1.5 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=1.5 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=1.5 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10

# sam ResNet18 widen_factor=2; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=2 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=2 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=0.5 --model.model_name=resnet18 --model.widen_factor=2 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10

# sam ResNet18 widen_factor=1; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10

# sam ResNet18 widen_factor=2; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=1.5 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=1.5 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=1.5 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10

# sam ResNet18 widen_factor=2; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=2 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=2 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10
python train.py config/train_sam.yaml --optimizer.opt_name=samen --optimizer.group=C --optimizer.condition=1.5 --model.model_name=resnet18 --model.widen_factor=2 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=sam-label-noise-cifar10