# sam ResNet18 widen_factor=1; label-noise 0.25; 0.5; 0.75; replicate each with 
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.25 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise

python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.5 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.5 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.5 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise

python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.75 --trainer.seed=42 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.75 --trainer.seed=43 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise
python train.py config/train_sam.yaml --model.model_name=resnet18 --model.widen_factor=1 --dataloader.data_name=cifar10 --dataloader.noise=0.75 --trainer.seed=44 --logging.framework_name=wandb --logging.project_name=cifar10-label-noise